swagger: "2.0"
info:
  title: v1/optimism-children-indexer.proto
  version: version not set
tags:
  - name: OptimismChildrenIndexerService
  - name: Health
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/deposits:
    get:
      operationId: OptimismChildrenIndexerService_GetDeposits
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1DepositsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: page
          in: query
          required: false
          type: string
          format: uint64
        - name: page_size
          in: query
          required: false
          type: string
          format: uint64
      tags:
        - OptimismChildrenIndexerService
  /api/v1/withdrawals:
    get:
      operationId: OptimismChildrenIndexerService_GetWithdrawals
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1WithdrawalsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: page
          in: query
          required: false
          type: string
          format: uint64
        - name: page_size
          in: query
          required: false
          type: string
          format: uint64
      tags:
        - OptimismChildrenIndexerService
  /health:
    get:
      summary: |-
        If the requested service is unknown, the call will fail with status
        NOT_FOUND.
      operationId: Health_Check
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1HealthCheckResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: service
          in: query
          required: false
          type: string
      tags:
        - Health
definitions:
  HealthCheckResponseServingStatus:
    type: string
    enum:
      - UNKNOWN
      - SERVING
      - NOT_SERVING
      - SERVICE_UNKNOWN
    default: UNKNOWN
    description: ' - SERVICE_UNKNOWN: Used only by the Watch method.'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1Deposit:
    type: object
    properties:
      init_tx:
        $ref: '#/definitions/v1TxInfo'
      from:
        type: string
      to:
        type: string
      mint:
        type: string
      value:
        type: string
      gas_limit:
        type: string
      is_creation:
        type: boolean
      execution_tx:
        $ref: '#/definitions/v1TxInfo'
      destination_chain_id:
        type: string
  v1DepositsResponse:
    type: object
    properties:
      items:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Deposit'
      pagination:
        $ref: '#/definitions/v1Pagination'
      next_page_params:
        $ref: '#/definitions/v1PaginationNextPage'
  v1HealthCheckResponse:
    type: object
    properties:
      status:
        $ref: '#/definitions/HealthCheckResponseServingStatus'
  v1Pagination:
    type: object
    properties:
      page:
        type: string
        format: uint64
      page_size:
        type: string
        format: uint64
      total_pages:
        type: string
        format: uint64
      total_items:
        type: string
        format: uint64
  v1PaginationNextPage:
    type: object
    properties:
      page:
        type: string
        format: uint64
      page_size:
        type: string
        format: uint64
  v1TxInfo:
    type: object
    properties:
      transaction_hash:
        type: string
      block_hash:
        type: string
      block_number:
        type: string
        format: uint64
      block_timestamp:
        type: string
      from:
        type: string
      to:
        type: string
      success:
        type: boolean
  v1Withdrawal:
    type: object
    properties:
      chain_id:
        type: string
      l3_block_number:
        type: string
        format: uint64
      l3_block_hash:
        type: string
      l3_block_timestamp:
        type: string
      l3_tx_hash:
        type: string
      nonce:
        type: string
      sender:
        type: string
      target:
        type: string
      value:
        type: string
      gas_limit:
        type: string
      data:
        type: string
      withdrawal_hash:
        type: string
      proving_tx:
        $ref: '#/definitions/v1WithdrawalProving'
      finalizing_tx:
        $ref: '#/definitions/v1WithdrawalFinalizing'
  v1WithdrawalFinalizedEvent:
    type: object
    properties:
      withdrawal_hash:
        type: string
      success:
        type: boolean
  v1WithdrawalFinalizing:
    type: object
    properties:
      metadata:
        $ref: '#/definitions/v1TxInfo'
      event:
        $ref: '#/definitions/v1WithdrawalFinalizedEvent'
  v1WithdrawalProvenEvent:
    type: object
    properties:
      withdrawal_hash:
        type: string
      from:
        type: string
      to:
        type: string
  v1WithdrawalProving:
    type: object
    properties:
      metadata:
        $ref: '#/definitions/v1TxInfo'
      event:
        $ref: '#/definitions/v1WithdrawalProvenEvent'
  v1WithdrawalsResponse:
    type: object
    properties:
      items:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Withdrawal'
      pagination:
        $ref: '#/definitions/v1Pagination'
      next_page_params:
        $ref: '#/definitions/v1PaginationNextPage'
