on:
  workflow_dispatch:

name: Publish types (golem-base-indexer)

permissions:
  id-token: write  # Required for OIDC (npmjs trusted publishing)
  contents: read
    
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish package to NPM registry
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Build the package
        working-directory: ./golem-base-indexer/types
        run: |
          npm ci
          npm run build

      - name: Publish to NPM registry
        working-directory: ./golem-base-indexer/types
        run: |
          npm publish --access public
